 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/slot_types", type: :request do
  # SlotType. As you add validations to SlotType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SlotType.create! valid_attributes
      get slot_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      slot_type = SlotType.create! valid_attributes
      get slot_type_url(slot_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_slot_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      slot_type = SlotType.create! valid_attributes
      get edit_slot_type_url(slot_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SlotType" do
        expect {
          post slot_types_url, params: { slot_type: valid_attributes }
        }.to change(SlotType, :count).by(1)
      end

      it "redirects to the created slot_type" do
        post slot_types_url, params: { slot_type: valid_attributes }
        expect(response).to redirect_to(slot_type_url(SlotType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SlotType" do
        expect {
          post slot_types_url, params: { slot_type: invalid_attributes }
        }.to change(SlotType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post slot_types_url, params: { slot_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested slot_type" do
        slot_type = SlotType.create! valid_attributes
        patch slot_type_url(slot_type), params: { slot_type: new_attributes }
        slot_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the slot_type" do
        slot_type = SlotType.create! valid_attributes
        patch slot_type_url(slot_type), params: { slot_type: new_attributes }
        slot_type.reload
        expect(response).to redirect_to(slot_type_url(slot_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        slot_type = SlotType.create! valid_attributes
        patch slot_type_url(slot_type), params: { slot_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested slot_type" do
      slot_type = SlotType.create! valid_attributes
      expect {
        delete slot_type_url(slot_type)
      }.to change(SlotType, :count).by(-1)
    end

    it "redirects to the slot_types list" do
      slot_type = SlotType.create! valid_attributes
      delete slot_type_url(slot_type)
      expect(response).to redirect_to(slot_types_url)
    end
  end
end
